### ISSUE TITLE
Use global moon binary over `node_modules` for VSCode extension

### ISSUE THREAD

**Issue by itsezc** [moonrepo/dev#27]
Since a user might have `moon` installed globally and setup on their PATH, the VSCode extension should ideally use this where possible.

Happy to take ownership for this issue.

**Comment by milesj** [comment]
I think we can just return `moon` here and everything _should_ just work: https://github.com/moonrepo/dev/blob/master/packages/vscode-extension/src/moon.ts#L21

**Comment by milesj** [comment]
Pushed something out. Let me know if it doesn't work!

**Comment by itsezc** [comment]
I've reinstalled the extension (on WSL) but using the `which moon` path just worked when replacing the path manually
