### ISSUE TITLE
Wondering why the target field in the ts configs use es2022 instead of esnext

### ISSUE THREAD

**Issue by TKDev7** [moonrepo/dev#40]
Just wondering why the target field in the ts configs use es2022 instead of esnext? Is there a specific reason for this?

**Comment by milesj** [comment]
The only reason really is that it's kept inline with the other tools: https://github.com/moonrepo/dev/blob/d2db67bde929a25f0ecdcb0ded58f850dce64523/packages/dev/src/constants.ts#L9
