### ISSUE TITLE
custom languages not allowed

### ISSUE THREAD

**Issue by thelittlebug** [moonrepo/dev#70]
in the docs https://moonrepo.dev/docs/config/project#language you can find `A custom language. Values will be converted to kebab-case.` but the linter does not like it:

![image](https://github.com/moonrepo/dev/assets/2874956/9a17b724-63b1-42da-b2cd-f35c876d8278)

**Comment by milesj** [comment]
I have a fix for this that will land in 1.24 hopefully.

**Comment by milesj** [comment]
Should be fixed in 1.24.
